PROJECT_SOURCE_DIR = multisip

DESIGN_SOURCE_DIR = ui
DESIGN_OUTPUT_DIR = ${PROJECT_SOURCE_DIR}

DESIGN_INPUT_FILES = $(wildcard ${DESIGN_SOURCE_DIR}/*.ui)
DESIGN_OUTPUT_FILES = $(patsubst %.ui,${DESIGN_OUTPUT_DIR}/%.py,$(DESIGN_INPUT_FILES))

all: ${DESIGN_OUTPUT_FILES}

${DESIGN_OUTPUT_DIR}/ui/%.py: ${DESIGN_SOURCE_DIR}/%.ui
	pyuic6 $< -o $@
