# Form implementation generated from reading ui file 'ui/add_user_agents.ui'
#
# Created by: PySide6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addUserAgentsGroupBox = QtWidgets.QGroupBox(parent=Form)
        self.addUserAgentsGroupBox.setObjectName("addUserAgentsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.addUserAgentsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.startNumberLabel = QtWidgets.QLabel(parent=self.addUserAgentsGroupBox)
        self.startNumberLabel.setObjectName("startNumberLabel")
        self.gridLayout.addWidget(self.startNumberLabel, 0, 0, 1, 1)
        self.startNumberInput = QtWidgets.QLineEdit(parent=self.addUserAgentsGroupBox)
        self.startNumberInput.setObjectName("startNumberInput")
        self.gridLayout.addWidget(self.startNumberInput, 0, 1, 1, 2)
        self.countLabel = QtWidgets.QLabel(parent=self.addUserAgentsGroupBox)
        self.countLabel.setObjectName("countLabel")
        self.gridLayout.addWidget(self.countLabel, 1, 0, 1, 1)
        self.countValue = QtWidgets.QSpinBox(parent=self.addUserAgentsGroupBox)
        self.countValue.setMinimum(1)
        self.countValue.setObjectName("countValue")
        self.gridLayout.addWidget(self.countValue, 1, 1, 1, 2)
        self.addUserAgentsButton = QtWidgets.QPushButton(parent=self.addUserAgentsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addUserAgentsButton.sizePolicy().hasHeightForWidth())
        self.addUserAgentsButton.setSizePolicy(sizePolicy)
        self.addUserAgentsButton.setObjectName("addUserAgentsButton")
        self.gridLayout.addWidget(self.addUserAgentsButton, 2, 0, 1, 2)
        self.cancelButton = QtWidgets.QPushButton(parent=self.addUserAgentsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.addUserAgentsGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addUserAgentsGroupBox.setTitle(_translate("Form", "Add User Agents"))
        self.startNumberLabel.setText(_translate("Form", "Start Number"))
        self.countLabel.setText(_translate("Form", "Count"))
        self.addUserAgentsButton.setText(_translate("Form", "Add"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
